# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2375298b091b34a9653b96bc2bb280138e9ad31c771dc61adfe967c81df3efbe63da160a983b85d45fdc9f2087948f38d975558234658c30562487277ccf3b57

test:
  secret_key_base: 1016d44bb5305e7b5e29f04cbb4e3a29296b094c1f96426b0267cc82394cb757742e9f9afa976506998e6280c363d57f10a40c5941414abf4b7465c5889d5c78

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
